config/routes.rb
Hamrochitwan::Application.routes.draw do

  resources :notifications, only: [:index, :update, :destroy]

  resources :contacts

  resources :buzzs
  resources :tags, only: [:index]

  resources :pages do
    put :feature_process
    get :gallery
  end

  resources :businesses

  resources :posts do
    resources :comments
    member do
      put :feature
    end
  end

  devise_for :users
  resources :users

  get '/search' => 'home#search', :as => :search
  get "/tags/:tag" => "posts#tagged_with", as: :tag
  get "/about" => "home#about", as: :about
  get "/social" => "home#social", as: :social

  namespace :admin do
    resources :home, :only => [:index]
    resources :posts, :only => [:approve]
    resources :feature do
      member do
        put :feature_process
      end
    end
  end

  
  root :to => 'home#index'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:index, :show]
  load_and_authorize_resource
  
  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @businesses }
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business = Business.find(params[:id])
    @total_pages = @business.pages.count
    @pages = @business.pages.order("created_at desc").page(params[:page]||1)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/new
  # GET /businesses/new.json
  def new
    @business = Business.new
    @business_parent = Business.where(parent_id: nil).select("id, title")
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
    @business_parent = Business.where(parent_id: nil).select("id, title")
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(params[:business])

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render json: @business, status: :created, location: @business }
      else
        format.html { render action: "new" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.json
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <label>Select the parent heading:</label>
    <%= select_tag "parent_id", options_from_collection_for_select(@business_parent, "id", "title") %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.haml
- title "Business Directory"
%h1 Business Directory
%hr
%table.table.table-bordered
  %tr
    %th #
    %th Title

  - @businesses.select{ |b| b.parent_id == nil }.each do |business|
    %tr.active
      %td
        = business.id
      %td
        = link_to business.title, business_path(business)
    - @businesses.select{ |b| b.parent_id == business.id }.each do |business|
      %tr
        %td
          = business.id
        %td
          = raw "&nbsp;&nbsp;&nbsp;&nbsp;#{link_to business.title, business_path(business)}"
%br
- if can? :create, Business
  = link_to 'Add New to Directory', new_business_path, class: 'btn btn-primary'

app/views/businesses/new.html.haml
%h1 Add A New To Business Directory
= render 'form'
= link_to 'Back', businesses_path

app/views/businesses/show.html.haml
.row
	.col-sm-12.col-md-12
		%h1
			Business Category:
			= @business.title
		%p= "#{@total_pages} Pages(s) Total"
		%ul.app-list
			- @pages.each do |page|
				%li
					%h3
						= link_to page.title, page.get_path
					%p.dim= AutoExcerpt.new(page.description, {words: 140,strip_html: true})
		= paginate @pages
		- if can? :manage, Business
			= link_to 'Edit', edit_business_path(@business), class: "btn btn-primary"
			= link_to 'Back', businesses_path, class: "btn btn-primary"