config/routes.rb
Hamrochitwan::Application.routes.draw do

  resources :notifications, only: [:index, :update, :destroy]

  resources :contacts

  resources :buzzs
  resources :tags, only: [:index]

  resources :pages do
    put :feature_process
    get :gallery
  end

  resources :businesses

  resources :posts do
    resources :comments
    member do
      put :feature
    end
  end

  devise_for :users
  resources :users

  get '/search' => 'home#search', :as => :search
  get "/tags/:tag" => "posts#tagged_with", as: :tag
  get "/about" => "home#about", as: :about
  get "/social" => "home#social", as: :social

  namespace :admin do
    resources :home, :only => [:index]
    resources :posts, :only => [:approve]
    resources :feature do
      member do
        put :feature_process
      end
    end
  end

  
  root :to => 'home#index'

end

app/views/shared/_nav.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}
        = image_tag "/images/hamrochitwan_text.png"
    .navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li{class: ("active" if controller_name=="posts")}
          %a{:href => "/posts"} Kinbech
        %li{class: ("active" if controller_name=="businesses")}
          %a{:href => "/businesses"} Business Directory
        %li{class: ("active" if controller_name=="pages")}
          %a{:href => "/pages"} Pages
        / %li.dropdown
        /   %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        /     Business Directory
        /     %b.caret
        /   %ul.dropdown-menu
        /     %li
        /       %a{:href => "#"} Action
        /     %li
        /       %a{:href => "#"} Another action
        /     %li
        /       %a{:href => "#"} Something else here
        /     %li.divider
        /     %li.dropdown-header Nav header
        /     %li
        /       %a{:href => "#"} Separated link
        /     %li
        /       %a{:href => "#"} One more separated link
        - if user_signed_in?
          %li{class: ("active" if controller_name=="notifications")}
            =link_to notifications_path, class: "notification" do
              Notifications
              - if notifications_count > 0
                %span.label.label-danger
                  = notifications_count
        %li{class: ("active" if controller_name=="home" && action_name=="social")}
          =link_to 'Social', social_path
      %ul.nav.navbar-nav.pull-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle.navbar-avatar{"data-toggle" => "dropdown", :href => "#"}
              = image_tag current_user.avatar_url(:thumb), class: "navbar-avatar-thumb"
              =current_user.full_name || current_user.email
              %b.caret
            %ul.dropdown-menu
              %li
                =link_to "My Profile", user_path(current_user.id)
              %li
                =link_to "My Posts", posts_path({filter: "my_posts"})
              %li
                =link_to "My Pages", pages_path({filter: "my_pages"})
              - if current_user.admin
                %li
                  =link_to "Ad Management", buzzs_path
                %li
                  =link_to "Admin", admin_home_index_path
                %li
                  =link_to "Messages", contacts_path
              %li
                = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to "Sign In", new_user_session_path
          %li
            = link_to "Sign Up", new_user_registration_path