config/routes.rb
Hamrochitwan::Application.routes.draw do

  resources :notifications, only: [:index, :update, :destroy]

  resources :contacts

  resources :buzzs
  resources :tags, only: [:index]

  resources :pages do
    put :feature_process
    get :gallery
  end

  resources :businesses

  resources :posts do
    resources :comments
    member do
      put :feature
    end
  end

  devise_for :users
  resources :users

  get '/search' => 'home#search', :as => :search
  get "/tags/:tag" => "posts#tagged_with", as: :tag
  get "/about" => "home#about", as: :about
  get "/social" => "home#social", as: :social

  namespace :admin do
    resources :home, :only => [:index]
    resources :posts, :only => [:approve]
    resources :feature do
      member do
        put :feature_process
      end
    end
  end

  
  root :to => 'home#index'

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController

	def index
		redirect_to root_path unless current_user.admin?
		@features = Post.where(hotdeal_status: Post::HOTDEAL_PENDING, status: Post::ACTIVE, hotdeal: true).page(params[:page])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	skip_before_filter :authenticate_user!
	layout 'social', :only => [:social]

	def index
		@latest_posts = Post.select('title, id, photo, slug, price, created_at').order("created_at desc").limit(10)
		@pages = Page.order("created_at desc").limit(10)
		@featured = Page.select('title, id, picture, slug').where(feature: true).order("created_at desc").limit(10)
	end

	def search
		@results = Page.search(params[:keywords]) + Post.search(params[:keywords])
	end

  def about
  end

  def social
  end

end

app/views/home/about.haml
- title "About Us"
%h1#about About
%section
  %p
    Hamrochitwan.com is FREE online portal(targeted for chitwan) which enables individuals as well as business houses to promote their market presence as well as showcase and sell wide variety of new or used products online. Apart from business related information, we also provide all round information about chiwan.

%h1#terms_of_use Terms of Use
%section
  %p
    Hamrochitwan.com do not guarantee the accuracy and disclaim liability for inaccuracies related to product and service information. Much of the information on product and service is provided by the respective suppliers and information provided is intended as only general guidelines. Hamrochitwan.com and its affiliates do not hold responsible of inaccuracies contained. Hamrochitwan.com attempt to be as accurate as possible in terms of product descriptions or other content of this site but do not hold guarantee that it is completely reliable and error-free. The suppliers providing product and services are independent contractors and not the employees of Hamrochitwan.com or its affiliates. As a condition of your use of this Web site, you warrant that you will not use this Web site for any purpose that is unlawful or prohibited by Government of Nepal. Our website may contain hyperlinks to Web sites operated by parties other than Hamrochitwan.com or its affiliates. Such hyperlinks are provided for your reference and we do not control such Web sites and we are not responsible for their contents or your use of them.
  %p
    Protecting privacy is important to us but due to the nature of our business, some functions and services offered through our site require that suppliers provide certain personal information such as email address, postal, phone numbers etc for communication purpose and the information collected by Hamrochitwan.com and its affiliates are the only information provided to us voluntarily.

%h1#buyer_protection Buyer Protection
%section
  %p
    We are dedicated to provide highest level of protection to our buyers. You are advised to follow these guidelines to ensure you are dealing with genuine sellers.
  %ul
    %li
      Always compare with your local market price and specification of any products you decide to buy.
    %li
      If the products are USED; always ask seller to upload photos, or email you the real images of the products.
    %li
      Comment on sellers and their products, it helps others to stay updated with the seller you deal with.
    %li
      Rather than private communication, make sure most of your dealings are made on public.
    %li
      If you have any complains about the products, sellers or content of our website, visit
      =link_to "Contact", new_contact_path
      page and select complain message type and send us your complain.

app/views/home/index.html.haml
- content_for :before_container do
  .jumbotron
    .container
      =image_tag "/images/hamrochitwan-logo.png", align: "left"
      %a{ href: "http://www.accuweather.com/en/np/bharatpur/244555/weather-forecast/244555", class: "aw-widget-legal"}
      .aw-widget-current{ id: "awcc1390048864486", "data-locationkey"=>"244555", "data-unit"=>"c", "data-language"=>"en-us", "data-useip"=>"false","data-uid"=>"awcc1390048864486"}
      %script{type: "text/javascript", src: "http://oap.accuweather.com/launch.js"}
.row.home
  .col-lg-8
    #carousel-feature.carousel.slide
      %ol.carousel-indicators
        - @featured.size.times do |i|
          %li{"data-target"=>"#carousel-feature","data-slide-to"=>"#{i}",class: ("active" if i == 0)}
      .carousel-inner
        - @featured.each_with_index do |feat, i|
          .item{class: ('active' if i == 0)}
            %img{:alt => "", :src => feat.picture_url}
            .carousel-caption
              =link_to feat.title, get_path(feat)
      %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-feature"}
        %span.icon-prev
      %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-feature"}
        %span.icon-next

    %h2 Latest in HamroChitwan

    .row.pinned_cols
      - @latest_posts.each do |post|
        .col-sm-6.col-md-6
          .thumbnail
            = link_to post do
              = image_tag post.photo_url(:thumb), alt: post.title
            .caption
              %h3= link_to post.title.capitalize, post
              %p
                %label.label.label-danger Rs. #{post.price}
                &nbsp;
                %label.label.label-warning #{time_ago_in_words post.created_at} ago
              %p
                <a target="_blank" href="http://www.facebook.com/sharer.php?u=#{post.get_path}" class="btn btn-primary btn-sm"> <i class="icon-facebook-sign"></i> Share this deal to your friends</a>
    %h2 Who's New

    .row.pinned_cols
      - @pages.each do |page|
        .col-sm-6.col-md-6
          .thumbnail.no-desc
            = link_to page do
              = image_tag page.picture_url, alt: page.title
            .caption
              %h3= link_to page.title.capitalize, page
    %p= link_to "View All Pages", pages_path, class: "btn btn-primary"
  .col-lg-4.sidebar
    .social-feed
      %a{href: "https://www.facebook.com/hamrochitwansite",class: "btn btn-primary", target: "_blank"}
        %i.icon-facebook-sign
        Find us in Facebook
    %br
    = render_cell :sidebar, :show
/ /container

app/views/home/search.html.haml
%h1= "We have #{@results.size} results(s) for you."
.row
	.col-md-12#search_form_wrap
		=form_tag search_path, method: :get, class: 'form-inline', id: 'search_form' do
			.form-group
				%label.sr-only{:for => "search_field"} Search
				%input.form-control{:placeholder => "Find in chitwan", :type => "search", name: 'keywords', value: params[:keywords], size: 100}
			%button.btn.btn-primary{:type => "submit"} Go
%ul.app-list
	- @results.each do |res|
		%li
			%h3
				%span.label.label-info= "In #{res.class == Post ? 'KinBech' : 'Business'}"
				= link_to res.title, res.get_path
			%p.dim= AutoExcerpt.new(res.description, {words: 40,strip_html: true})

app/views/home/social.html.erb
<h1>Chitwan Social Feed</h1>
<hr />
<style type="text/css">
  .tab-content{
    padding: 10px;
    background: #fff;
    border: 1px solid #ccc;
    margin-top: -1px;
    line-height: 1.5em;
  }
</style>
<!-- Nav tabs -->
<ul class="nav nav-tabs">
  <li class="active"><a href="#facebook" data-toggle="tab"><i class="icon icon-facebook"></i> Facebook</a></li>
  <li><a href="#youtube" data-toggle="tab"><i class="icon icon-youtube"></i> Youtube</a></li>
  <li><a href="#news" data-toggle="tab"><i class="icon icon-th"></i> News</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane active" id="facebook">
    <ul id="facebook-posts">

      <!-- ko foreach:posts -->
      <li class="post">

        <div class="source">
          <a class="profile-picture" data-bind="attr: {'href': 'http://www.facebook.com/profile.php?id='+from.id, 'title': from.name}" target="_blank">
              <img data-bind="attr: {'src': 'http://graph.facebook.com/'+from.id+'/picture?height=64&width=64', 'alt': from.name}">
          </a>
        </div>
        <div class="story">
          <a data-bind="attr: {'href': 'http://www.facebook.com/profile.php?id='+from.id, 'title': from.description}, text: from.name" target="_blank" class="author">
          </a>
          <br>
          <!-- ko if:type=='status' -->
          <div class="message" data-bind="truncate: message, parse_tags: message_tags"></div>
          <!-- /ko -->

          <!-- ko if:typeof story!='undefined' -->
          <div data-bind="truncate: story" class="message"></div>
          <!-- /ko -->
          
          <!-- ko if:type=='video' -->
            <div class="video-post clearfix">
                <div class="link">
                <a href="javascript:void(0)" data-bind="click: play_video" title="Click to play video"  class="video-thumb">
                  <!-- ko if:typeof picture!='undefined' -->
                    <img data-bind="attr: {'src': picture}">
                  <!-- /ko -->
                </a>
                </div>
                <div class="media-caption">
                <!-- ko if:typeof link!='undefined' -->
                  <a data-bind="attr: {'href': link}" target="_blank">
                    <span data-bind="truncate: message, parse_tags: message_tags"></span>
                    <!-- ko if:typeof properties!='undefined' -->
                      (<span data-bind="text: properties[0].text"></span>)
                    <!-- /ko -->
                  </a>
                <!-- /ko -->
                </div>
            </div>
          <!-- /ko -->

          <!-- ko if:type=='photo' -->
            <div class="photo-post clearfix">
            <!-- ko if:typeof message!='undefined' -->
            <div class="message" data-bind="truncate: message, parse_tags: message_tags"></div>
            <!-- /ko -->
            <div class="link">
            <a data-bind="attr: {'href': link}" target="_blank" title="Click to view photo on Facebook">
                <img data-bind="attr: {'src': 'http://graph.facebook.com/'+ object_id+'/picture?width=64&height=64'}" align="left">
            </a>
            </div>
            <!-- ko if:typeof caption!='undefined' -->
              <div class="media-caption message" data-bind="truncate: caption"></div>
            <!-- /ko -->
            </div>
          <!-- /ko -->

          <!-- ko if:type=='link' -->
            <div class="link-post clearfix">
            <!-- ko if:typeof message!='undefined' -->
            <div data-bind="truncate: message" class="message"></div>
            <!-- /ko -->

            <div class="link">
              <!-- ko if:typeof picture!='undefined' -->
              <a data-bind="attr: {'href': link}" class="link-img">
                  <img data-bind="attr: {'src': picture, 'alt': name}">
              </a>
              <!-- /ko -->
            </div>
            <div class="media-caption">
                <!-- ko if:typeof name!='undefined' -->
                <a data-bind="attr: {'href': link}, text: name"></a>
                <!-- /ko -->
                <!-- ko if:name=='' -->
                <a data-bind="attr: {'href': link}, text: message"></a>
                <!-- /ko -->
                <!-- ko if:typeof caption!='undefined' -->
                <div class="caption" data-bind="text: caption"></div>
                <!-- /ko -->
                <!-- ko if:typeof description!='undefined' -->
                <div class="description" data-bind="truncate: description"></div>
                <!-- /ko -->
              </div>
            </div>
          <!-- /ko -->

          <div class="meta">

            <!-- ko if:typeof likes!='undefined' -->
            <span data-bind="text: likes.data.length"></span> <span data-bind="pluralize: likes.data.length">like</span> | 
            <!-- /ko -->

            <!-- ko if:typeof shares!='undefined' -->
            <span data-bind="text: shares.count"></span> <span data-bind="pluralize: shares.count">share</span> | 
            <!-- /ko -->

            <span class="time" data-bind="text: get_relative_time(fb_format_time(created_time))"></span>

            <!-- ko if:typeof place!='undefined' -->
            from <span class="place" data-bind="text: place.name"></span>
            <!-- /ko -->

            <!-- ko if:typeof application!='undefined' -->
            via <span class="app" data-bind="text: application.name"></span>
            <!-- /ko -->
          </div>

        </di>

      </li>
      <!-- /ko -->

    </ul>
  </div>
  <div class="tab-pane" id="youtube">
    <h2>Youtube Feed Coming Soon ...</h2>
  </div>
  <div class="tab-pane" id="news">
    <h2>News Feed Coming Soon ...</h2>
  </div>
</div>