config/routes.rb
Hamrochitwan::Application.routes.draw do

  resources :notifications, only: [:index, :update, :destroy]

  resources :contacts

  resources :buzzs
  resources :tags, only: [:index]

  resources :pages do
    put :feature_process
    get :gallery
  end

  resources :businesses

  resources :posts do
    resources :comments
    member do
      put :feature
    end
  end

  devise_for :users
  resources :users

  get '/search' => 'home#search', :as => :search
  get "/tags/:tag" => "posts#tagged_with", as: :tag
  get "/about" => "home#about", as: :about
  get "/social" => "home#social", as: :social

  namespace :admin do
    resources :home, :only => [:index]
    resources :posts, :only => [:approve]
    resources :feature do
      member do
        put :feature_process
      end
    end
  end

  
  root :to => 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :page
  has_many :comments, :as => :commentable
  attr_accessible :condition, :description, :expiry_date, :hotdeal, :home_delivery, :photo, :photo_cache, :price, :status, :title, :used_for, :hotdeal_expiry, :hotdeal_status, :tag_list, :page_id

  validates_presence_of :title, :description, :price

  mount_uploader :photo, PostPhotoUploader

  extend Searcher

  extend FriendlyId
  friendly_id :title,use: :slugged

  acts_as_taggable

  ACTIVE    = 0
  SOLD			= 1
  EXPIRED		= 2

  STATUSES = {
  	0 => "active",
  	1 => "sold",
  	2 => "expired"
  }

  HOTDEAL_COLD    = 0
  HOTDEAL_PENDING = 1
  HOTDEAL_ACTIVE  = 2
  HOTDEAL_SPECIAL = 3

  HOTDEAL_STATUSES = {
    0 => "cold",
    1 => "pending",
    2 => "active",
    3 => "special"
  }

  CONDITIONS = ["Excellent", "Good", "Fair", "Needs Repair", "Parts need to replaced"]

  def nice_status
  	STATUSES[self.status]
  end

  def nice_hotdeal_status
    HOTDEAL_STATUSES[self.hotdeal_status]
  end

  def get_path
    "/posts/#{self.slug}"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:index, :show, :tagged_with]
  load_and_authorize_resource

  def feature
    @post = Post.find(params[:id])
    feature = params[:feature_action] == "feature"
    feature_param = {hotdeal: feature}
    feature_param.merge!(hotdeal_status: Post::HOTDEAL_PENDING) if feature
    @post.update_attributes(feature_param)
    redirect_to @post, notice: feature ? "The post has been requested for the hotdeal." : "The post has been removed from hotdeal."
  end

  def tagged_with
    @posts = Post.tagged_with(params[:tag])
  end


  # GET /posts
  # GET /posts.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: PostsDatatable.new(view_context) }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id], include: [:user])
    @comments = @post.comments.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @pages = current_user.pages.select('id, title')
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @pages = current_user.pages.select('id, title')
  end

  # POST /posts
  # POST /posts.json
  def create
    params[:post][:expiry_date] = params[:post][:expiry_date].present? ? DateTime.parse(params[:post][:expiry_date]) : (Time.now + 30.days)
    params[:post].merge!(hotdeal_status: Post::HOTDEAL_PENDING) if params[:post][:hotdeal]
    @post = current_user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    params[:post].merge!(hotdeal_status: Post::HOTDEAL_PENDING) if params[:post][:hotdeal] == "1"
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, :html => {:multipart => true} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">

      <div class="col-md-6">
        <div class="field">
          <%= f.label :title %><br />
          <%= f.text_field :title, class: "full-width", required: true%>
        </div>
        <br>
        <div class="field">
          <%= f.label :description %><br />
          <%= f.text_area :description, rows: 10, class: "full-width redactor", required: true %>
        </div>
        <br>
        <div class="field">
          <label>Add a picture</label>
          <br>
          <%= image_tag @post.photo_url(:thumb) unless @post.photo.blank? %>
          <%= f.file_field :photo, value: @post.photo_url(:thumb) %>
          <%= f.hidden_field :photo_cache %>
        </div>
        <br>
        <div class="field">
          <label>Add Tags</label>
          <%= f.hidden_field :tag_list %>
          <small>Type your tag and hit enter, you can enter as many tags as relevant</small>
        </div>
      </div>
      <div class="col-md-3">
        <div class="field">
          <%= f.label :used_for %><br />
          <%= f.text_field :used_for %>
          <small>Eg. 3 months, 1 year</small>
        </div>
        <br>
        <div class="field">
          <%= f.label :condition %><br />
          <%= f.select :condition, Post::CONDITIONS %>
        </div>
        <br>
        <div class="field">
          <%= f.label :expiry_date %><br />
          <%= f.text_field :expiry_date, placeholder: "30 days from now if not set" %>
        </div>
        <% unless @pages.empty? %>
        <br>
        <div class="field">
          <%= f.label "Page" %><br />
          <% @pages.prepend(OpenStruct.new(id: "", title: "None")) %>
          <%= f.select :page_id, options_from_collection_for_select(@pages, "id", "title", @post.page_id) %>
          <br>
          <small>We found that you have pages also. You can link this post to your pages. The linked items will appear in the page also.</small>
        </div>
        <% end %>
      </div>
      <div class="col-md-3">
        <div class="field">
          <%= f.label :price %><br />
          <%= f.text_field :price, placeholder: "In Rupees", required: true %>
        </div>
        <br>
        <div class="field">
          <%= f.check_box :home_delivery %>
          <%= f.label :home_delivery %>
        </div>
        <div class="field" >
          <%= f.check_box :hotdeal %>
          <%= f.label :hotdeal %>
          <br>
          <small>Hot Deals should be approved by admin before it gets featured. Deals will be approved within 5 days. A picture is compulary for a post to become HotDeal.</small>
        </div>       
      </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-12">
        <div class="actions">
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to 'Cancel', posts_path %>
        </div>
      </div>
  </div>
<% end %>
<script type="text/javascript">
  $(function(){
    var date = new Date();
    var datestring = ("0" +date.getDate().toString()).substr(-2)  + "-" + ("0" + (date.getMonth() + 1).toString()).substr(-2)+ "-" + (date.getFullYear().toString());
    $('#post_expiry_date').datepicker({
      format: 'dd-mm-yyyy',
      todayBtn: 'linked',
      startDate: datestring
    });

    $('#post_tag_list').tagit({
        tagSource: function(search, showChoices) {
          var that = this;
          $.ajax({
            url: "/tags",
            data: {q: search.term},
            success: function(choices) {
              showChoices(that._subtractArray(choices, that.assignedTags()));
            }
          });
        },
    });
  });
</script>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<hr>
<%= render 'form' %>

app/views/posts/index.html.haml
- title 'All Posts'
%h1 Listing All Posts
%hr
.row
  .col-md-8
    %br
    %ul.nav.nav-pills
      %li{class: ("active" unless params[:filter] || params[:filter] == "all_posts" )}
        =link_to "All Posts", "?filter=all_posts"
      - if user_signed_in?
        %li{class: ("active" if params[:filter] == "my_posts")}
          =link_to "My Posts", "?filter=my_posts"
    %hr

    %table.datatable.table#posts_datatable
      %thead
        %tr
          %th
          %th
          %th
          %th
      %tbody


  .col-md-4.sidebar
    %p
      = link_to 'Add A New Post', new_post_path, class: "btn btn-primary"
    = render_cell :sidebar, :show

app/views/posts/new.html.haml
%h1 New Post
%hr
= render 'form'

app/views/posts/show.html.haml
- title "#{@post.title}"
.row
  .col-sm-12.col-md-12
    %h1
      = @post.title.capitalize
    %b.pull-left{style: "margin-top: 2px"}
      = link_to  "By: #{@post.user.full_name || @post.user.email}", user_path(@post.user)
    &nbsp;
    %span.label.label-info
      = "#{time_ago_in_words @post.created_at} ago"
    - if @post.hotdeal && @post.nice_hotdeal_status == "active"
      &nbsp;
      %span.label.label-warning HotDeal
%br
.row
  .col-md-3
    = link_to @post.photo_url, class: "fancybox", title: @post.title do
      = image_tag @post.photo_url, class: "img-thumbnail"
    %div.tags-div
      %strong Tags:
      = raw @post.tag_list.map{ |t| link_to(t, tag_path(t)) }.join(', ')
  .col-md-9
    .row
      .col-md-8
        .share-wrap
          / AddThis Button BEGIN
          .addthis_toolbox.addthis_default_style
            %a.addthis_button_facebook_like{"fb:like:layout" => "button_count"}
            %a.addthis_button_tweet
          :javascript
            var addthis_config = {"data_track_addressbar":true};
          %script{src: "//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-52e276631daabd07", type: "text/javascript"}
          / AddThis Button END
        %section.user_content
          = simple_format @post.description
      .col-md-4
        .posts-info-note
          %p
            %b Status:
            = @post.nice_status
          %p
            %b Price:
            Rs. #{@post.price}
          %p
            %b Home Delivery:
            = @post.home_delivery ? "Yes" : "No"
          %p
            %b Expiry Date:
            = @post.expiry_date.strftime('%d %B, %Y')
          %p
            %b Condition:
            = @post.condition
          %p
            %b Used For:
            = @post.used_for

%hr
.comments_wrap
  - @comments.each do |comment|
    %p
      - user = comment.user
      = link_to user do
        = image_tag user.avatar_url(:thumb), height: '40px', width: "40px"
        %b="#{user.full_name || user.email}:"
      = comment.content
%h2
  Add a New Comment
  - unless user_signed_in?
    %small You need to sign up for this action.
= form_for [@post, Comment.new] do |form|
  %p
    = form.text_area :content, :rows => 5, required: true
  %p
    = submit_tag "Add comment", class: "btn btn-primary", disabled: !user_signed_in?
%hr
-if can? :update, @post
  = link_to 'Edit', edit_post_path(@post), class: "btn btn-primary"
  - if @post.hotdeal && @post.hotdeal_status == Post::HOTDEAL_PENDING
    = link_to "Approval Pending for HotDeal", "", disabled: true, class: "btn btn-default"
  - else
    = link_to (@post.hotdeal ? 'Remove Hotdeal' : 'Make HotDeal'), feature_post_path(@post,{feature_action: (@post.hotdeal ? 'unfeature' : 'feature')}), class: "btn btn-warning", method: :put
-if can? :destroy, @post
  = link_to 'Destroy', @post, class: "button btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }

app/views/posts/tagged_with.html.haml
%h1
	Listing All Posts with tag-
	%strong #{params[:tag]}
.row
	.col-md-8
		%ul.app-list
			- @posts.each do |post|
				%li
					%h3= link_to post.title, post_path(post)
					%p= AutoExcerpt.new(post.description, {words: 180,strip_html: true})
					%div
						%span.label.label-info By: #{post.user.email}
						%span.label.label-default #{time_ago_in_words post.created_at} ago
						%span.label.label-warning Price: Rs. #{post.price}
						.pull-right
							%span.label.label-success Status: #{post.nice_status}
	.col-md-4.sidebar
		%p
			= link_to 'Add A New Post', new_post_path, class: "btn btn-primary"
		= render_cell :sidebar, :show